name: em
channels:
  - conda-forge
  - defaults
dependencies:
  - git
  - pip
  - mkl-devel
  - pkg-config
  - cmake
  - cython 
  - ninja
  - matplotlib
  - mtpy-v2
  - pydiso
  - dill
  - jupyterlab
  - ipywidgets
  
  
