name: em
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - git
  - pip
  - mkl-devel
  - pkg-config
  - cmake
  - cython 
  - ninja
  - matplotlib
  - simpeg>=0.22
  - mtpy-v2>=2.0.12
  - pydiso
  - dill
  - jupyterlab
  - ipywidgets
  
  
